In [4]:
!ls

Aditya Birla Sun Life Mutual Fund.txt
age Data
CPI.XLSX
currency.csv
Data Merging.ipynb
data observing.ipynb
Deliverables.docx
featurestry.py
filewisefund.npy
fundtype
fundtypedata.npy
fundtypenames.npy
fundwisefile.npy
gc.sublime-workspace
Gdp.csv
GDP.XLSX
givenschemes.csv
HDFC Mutual Fund.txt
ICICI Prudential Mutual Fund.txt
ind.ipynb
Instruction to get Mutual Fund data.docx
Marking Scheme - Inter Hall IIT KGP.docx
MF_IIT_DATA_V1.csv
Problem Statement - Inter Hall IIT KGP.docx
Reliance Mutual Fund.txt
SBI Mutual Fund.txt
SchemeData.csv
schemesexp
schemes.pkl
sector Data
Sundaram Mutual Fund.txt
Tata Mutual Fund.txt
Untitled1.ipynb
Untitled2.ipynb
Untitled.ipynb
UTI Mutual Fund.txt

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
% matplotlib inline
import tqdm as tqdm
import os
import pickle as pkl

In [4]:
data = pkl.load(open('fundtype/fundwise.pkl', 'rb'))

In [5]:
names = []
for i in range(12):
    names.append(data[i]['Scheme Name'].values)

In [6]:
ids = []
c = 0
for i in names:
    c += len(i)
    ids.append(c)

In [7]:
scheme = []
for i in names:
    scheme = np.append(scheme, i)

In [8]:
def create(given, val, names, data, ids, n):
    temp = []
    for i, p in tqdm.tqdm(enumerate(names)):
        c = 0
        for j in range(len(given)):
            if given[j] == p:
                temp.append(val[j])
                c = 1
        if c == 0:
            temp.append(np.nan)
    f = sep(temp, ids)
    for i in range(12):
        data[i][n] = f[i]
    return data

In [9]:
d = pd.read_csv('givenschemes.csv')

In [10]:
d

,Unnamed: 0,AMC,Code,Scheme.Name,Scheme.Type,Scheme.Category,Scheme.NAV.Name,Scheme.Minimum.Amount,Launch.Date,Closure.Date,ISIN.Div.Payout..ISIN.GrowthISIN.Div.Reinvestment
0,2486,Aditya Birla Sun Life AMC Limited,120533,Aditya Birla Sun Life Banking & PSU Debt Fund,Open Ended,Income,Aditya Birla Sun Life Banking & PSU Debt Fund ...,1000,15-Oct-99,NaN,INF209K01YL4
1,2488,Aditya Birla Sun Life AMC Limited,103188,Aditya Birla Sun Life Banking & PSU Debt Fund,Open Ended,Income,Aditya Birla Sun Life Banking & PSU Debt Fund ...,1000,15-Oct-99,NaN,INF209K01BF4
2,2490,Aditya Birla Sun Life AMC Limited,133440,Aditya Birla Sun Life Banking & PSU Debt Fund,Open Ended,Income,Aditya Birla Sun Life Banking & PSU Debt Fund ...,1000,15-Oct-99,NaN,INF209K01YJ8
3,2489,Aditya Birla Sun Life AMC Limited,133439,Aditya Birla Sun Life Banking & PSU Debt Fund,Open Ended,Income,Aditya Birla Sun Life Banking & PSU Debt Fund ...,1000,15-Oct-99,NaN,INF209KA1WN8
4,2487,Aditya Birla Sun Life AMC Limited,103187,Aditya Birla Sun Life Banking & PSU Debt Fund,Open Ended,Income,Aditya Birla Sun Life Banking & PSU Debt Fund ...,1000,15-Oct-99,NaN,INF209K01BE7INF209K01EA9
5,2485,Aditya Birla Sun Life AMC Limited,120532,Aditya Birla Sun Life Banking & PSU Debt Fund,Open Ended,Income,Aditya Birla Sun Life Banking & PSU Debt Fund ...,1000,15-Oct-99,NaN,INF209K01YK6
6,2494,Aditya Birla Sun Life AMC Limited,119524,Aditya Birla Sun Life Cash Manager,Open Ended,Income,Aditya Birla Sun Life Cash Manager - Daily Div...,5000,07-Jul-98,NaN,INF209K01XW3
7,2495,Aditya Birla Sun Life AMC Limited,113307,Aditya Birla Sun Life Cash Manager,Open Ended,Income,Aditya Birla Sun Life Cash Manager - Daily Div...,5000,07-Jul-98,NaN,INF209K01KH1
8,2493,Aditya Birla Sun Life AMC Limited,119523,Aditya Birla Sun Life Cash Manager,Open Ended,Income,Aditya Birla Sun Life Cash Manager - Growth - ...,5000,07-Jul-98,NaN,INF209K01XU7
9,2497,Aditya Birla Sun Life AMC Limited,103192,Aditya Birla Sun Life Cash Manager,Open Ended,Income,Aditya Birla Sun Life Cash Manager - Growth Plan,5000,07-Jul-98,NaN,INF209K01LQ0
10,2496,Aditya Birla Sun Life AMC Limited,103191,Aditya Birla Sun Life Cash Manager,Open Ended,Income,Aditya Birla Sun Life Cash Manager - Instituti...,5000,07-Jul-98,NaN,INF209K01KD0
11,2500,Aditya Birla Sun Life AMC Limited,103195,Aditya Birla Sun Life Cash Manager,Open Ended,Income,Aditya Birla Sun Life Cash Manager - Instituti...,5000,07-Jul-98,NaN,INF209K01KE8
12,2499,Aditya Birla Sun Life AMC Limited,103194,Aditya Birla Sun Life Cash Manager,Open Ended,Income,Aditya Birla Sun Life Cash Manager - Instituti...,5000,07-Jul-98,NaN,INF209K01KG3
13,2492,Aditya Birla Sun Life AMC Limited,119522,Aditya Birla Sun Life Cash Manager,Open Ended,Income,Aditya Birla Sun Life Cash Manager - Weekly Di...,5000,07-Jul-98,NaN,INF209K01XV5
14,2498,Aditya Birla Sun Life AMC Limited,103193,Aditya Birla Sun Life Cash Manager,Open Ended,Income,Aditya Birla Sun Life Cash Manager - Weekly Di...,5000,07-Jul-98,NaN,INF209K01KF5
15,11683,Aditya Birla Sun Life AMC Limited,134388,Aditya Birla Sun Life Corporate Bond Fund,Open Ended,Income,Aditya Birla Sun Life Corporate Bond Fund - Di...,Rs. 5000 and in multiples of re. 1/-,30-Mar-15,NaN,INF209KA1L12
16,11680,Aditya Birla Sun Life AMC Limited,134385,Aditya Birla Sun Life Corporate Bond Fund,Open Ended,Income,Aditya Birla Sun Life Corporate Bond Fund - Di...,Rs. 5000 and in multiples of re. 1/-,30-Mar-15,NaN,INF209KA1K96INF209KA1L04
17,11682,Aditya Birla Sun Life AMC Limited,134387,Aditya Birla Sun Life Corporate Bond Fund,Open Ended,Income,Aditya Birla Sun Life Corporate Bond Fund - Di...,Rs. 5000 and in multiples of re. 1/-,30-Mar-15,NaN,INF209KA1K88
18,11679,Aditya Birla Sun Life AMC Limited,134384,Aditya Birla Sun Life Corporate Bond Fund,Open Ended,Income,Aditya Birla Sun Life Corporate Bond Fund - Re...,Rs. 5000 and in multiples of re. 1/-,30-Mar-15,NaN,INF209KA1K70
19,11681,Aditya Birla Sun Life AMC Limited,134386,Aditya Birla Sun Life Corporate Bond Fund,Open Ended,Income,Aditya Birla Sun Life Corporate Bond Fund - Re...,Rs. 5000 and in multiples of re. 1/-,30-Mar-15,NaN,INF209KA1K54INF209KA1K62
20,11678,Aditya Birla Sun Life AMC Limited,134383,Aditya Birla Sun Life Corporate Bond Fund,Open Ended,Income,Aditya Birla Sun Life Corporate Bond Fund - Re...,Rs. 5000 and in multiples of re. 1/-,30-Mar-15,NaN,INF209KA1K47
21,2158,Aditya Birla Sun Life AMC Limited,132918,Aditya Birla Sun Life Dynamic Bond Fund,Open Ended,Income,Aditya Birla Sun Life Dynamic Bond Fund - Dire...,5000,10-Sep-04,NaN,INF209KA1TX3
22,2156,Aditya Birla Sun Life AMC Limited,119505,Aditya Birla Sun Life Dynamic Bond Fund,Open Ended,Income,Aditya Birla Sun Life Dynamic Bond Fund - Grow...,5000,10-Sep-04,NaN,INF209K01N82
23,2151,Aditya Birla Sun Life AMC Limited,102767,Aditya Birla Sun Life Dynamic Bond Fund,Open Ended,Income,Aditya Birla Sun Life Dynamic Bond Fund - Grow...,5000,10-Sep-04,NaN,INF209K01793
24,2155,Aditya Birla Sun Life AMC Limited,119503,Aditya Birla Sun Life Dynamic Bond Fund,Open Ended,Income,Aditya Birla Sun Life Dynamic Bond Fund - Mont...,5000,10-Sep-04,NaN,INF209K01R62
25,2153,Aditya Birla Sun Life AMC Limited,111521,Aditya Birla Sun Life Dynamic Bond Fund,Open Ended,Income,Aditya Birla Sun Life Dynamic Bond Fund - Mont...,5000,10-Sep-04,NaN,INF209K01801INF209K01DG8
26,2154,Aditya Birla Sun Life AMC Limited,119502,Aditya Birla Sun Life Dynamic Bond Fund,Open Ended,Income,Aditya Birla Sun Life Dynamic Bond Fund - Quar...,5000,10-Sep-04,NaN,INF209K01R88
27,2150,Aditya Birla Sun Life AMC Limited,102766,Aditya Birla Sun Life Dynamic Bond Fund,Open Ended,Income,Aditya Birla Sun Life Dynamic Bond Fund - Quar...,5000,10-Sep-04,NaN,INF209K01819INF209K01DH6
28,2157,Aditya Birla Sun Life AMC Limited,132917,Aditya Birla Sun Life Dynamic Bond Fund,Open Ended,Income,Aditya Birla Sun Life Dynamic Bond Fund - Regu...,5000,10-Sep-04,NaN,INF209KA1TV7
29,2152,Aditya Birla Sun Life AMC Limited,111848,Aditya Birla Sun Life Dynamic Bond Fund,Open Ended,Income,Aditya Birla Sun Life Dynamic Bond Fund-Discip...,5000,10-Sep-04,NaN,INF209K01JW2
...,...,...,...,...,...,...,...,...,...,...,...
2400,1983,UTI Asset Management Company Ltd,120791,UTI - GILT ADVANTAGE,Open Ended,Gilt,UTI - GILT ADVANTAGE-LONG TERM-DIVIDEND- Direct,5000/-,14-Jan-01,NaN,INF789F01TJ9INF789F01TK7
2401,1976,UTI Asset Management Company Ltd,102510,UTI - GILT ADVANTAGE,Open Ended,Gilt,UTI - GILT ADVANTAGE-LONG TERM-GROWTH,5000/-,14-Jan-01,NaN,INF789F01661
2402,1984,UTI Asset Management Company Ltd,120792,UTI - GILT ADVANTAGE,Open Ended,Gilt,UTI - GILT ADVANTAGE-LONG TERM-GROWTH- Direct,5000/-,14-Jan-01,NaN,INF789F01TL5
2403,677,UTI Asset Management Company Ltd,120715,UTI - Long Term Equity Fund (Tax Saving),Open Ended,ELSS,UTI - Long Term Equity Fund (Tax Saving) - Dir...,Rs 500/-,15-Nov-99,NaN,INF789F01TF7
2404,674,UTI Asset Management Company Ltd,100820,UTI - Long Term Equity Fund (Tax Saving),Open Ended,ELSS,UTI - Long Term Equity Fund (Tax Saving) - Reg...,Rs 500/-,15-Nov-99,NaN,INF789F01521INF789F01539
2405,675,UTI Asset Management Company Ltd,100821,UTI - Long Term Equity Fund (Tax Saving),Open Ended,ELSS,UTI - Long Term Equity Fund (Tax Saving) - Reg...,Rs 500/-,15-Nov-99,NaN,INF789F01547
2406,676,UTI Asset Management Company Ltd,120714,UTI - Long Term Equity Fund (Tax Saving),Open Ended,ELSS,UTI - Long Term Equity fund (Tax Saving) Direc...,Rs 500/-,15-Nov-99,NaN,INF789F01TD2INF789F01TE0
2407,2001,UTI Asset Management Company Ltd,134484,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - Floating Rate STP - Annual Div Option,5000/-,29-Aug-03,NaN,INF789FA1P43INF789FA1P50
2408,2003,UTI Asset Management Company Ltd,139568,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - Floating Rate STP - Direct Plan - Annual...,5000/-,29-Aug-03,NaN,INF789FA1Q42INF789FA1Q59
2409,1998,UTI Asset Management Company Ltd,131511,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - Floating Rate STP - Fortnightly Div Option,5000/-,29-Aug-03,NaN,INF789FA1O69INF789FA1O77
2410,1999,UTI Asset Management Company Ltd,131512,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - Floating Rate STP - Fortnightly Div Opti...,5000/-,29-Aug-03,NaN,INF789FA1P68INF789FA1P76
2411,2000,UTI Asset Management Company Ltd,134799,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - Floating Rate STP - Half Yearly Div Option,5000/-,29-Aug-03,NaN,INF789FA1P27INF789FA1P35
2412,1993,UTI Asset Management Company Ltd,112083,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - FLOATING RATE STP - INSTN GROWTH OPTION,5000/-,29-Aug-03,NaN,INF789F01PM1
2413,1992,UTI Asset Management Company Ltd,112082,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - FLOATING RATE STP - INSTN PLAN - PERIODI...,5000/-,29-Aug-03,NaN,INF789F01PL3
2414,1996,UTI Asset Management Company Ltd,131445,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - Floating Rate STP - Monthly Div Option,5000/-,29-Aug-03,NaN,INF789FA1O85INF789FA1O93
2415,1995,UTI Asset Management Company Ltd,131444,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - Floating Rate STP - Monthly Div Option -...,5000/-,29-Aug-03,NaN,INF789FA1P84INF789FA1P92
2416,2002,UTI Asset Management Company Ltd,133873,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - Floating Rate STP - Quarterly Div Option,5000/-,29-Aug-03,NaN,INF789FA1P01INF789FA1P19
2417,1997,UTI Asset Management Company Ltd,133059,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - Floating Rate STP - Quarterly Div Option...,5000/-,29-Aug-03,NaN,INF789FA1Q00INF789FA1Q18
2418,1988,UTI Asset Management Company Ltd,121891,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - FLOATING RATE STP -Regular Plan (Flexi D...,5000/-,29-Aug-03,NaN,INF789FB1KS6INF789FB1KT4
2419,1989,UTI Asset Management Company Ltd,121892,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - FLOATING RATE STP -Regular Plan (Flexi D...,5000/-,29-Aug-03,NaN,INF789FB1KQ0INF789FB1KR8
2420,1994,UTI Asset Management Company Ltd,109501,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - FLOATING RATE STP-DAILY DIVIDEND,5000/-,29-Aug-03,NaN,INF789F01554
2421,1985,UTI Asset Management Company Ltd,120744,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - FLOATING RATE STP-DAILY DIVIDEND-Direct,5000/-,29-Aug-03,NaN,INF789F01TG5INF789F01TH3
2422,1990,UTI Asset Management Company Ltd,102531,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - FLOATING RATE STP-DIVIDEND,5000/-,29-Aug-03,NaN,INF789F01562
2423,1991,UTI Asset Management Company Ltd,102532,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - FLOATING RATE STP-GROWTH,5000/-,29-Aug-03,NaN,INF789F01570
2424,1987,UTI Asset Management Company Ltd,120746,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - FLOATING RATE STP-GROWTH-direct,5000/-,29-Aug-03,NaN,INF789F01TI1
2425,1986,UTI Asset Management Company Ltd,120745,UTI - FLOATING RATE STP,Open Ended,Floating Rate,UTI - FLOATING RATE STP-Weekly Dividend- Direct,5000/-,29-Aug-03,NaN,INF789FB1S63
2426,2968,UTI Asset Management Company Ltd,105463,UTI GOLD Exchange Traded Fund,Open Ended,GOLD ETFs,UTI GOLD Exchange Traded Fund,20000,01-Mar-07,NaN,INF78901059
2427,12272,UTI Asset Management Company Ltd,135320,UTI NIFTY Exchanage Traded Fund,Open Ended,Other ETFs,UTI NIFTY Exhcange Traded Fund,During NFO Rs 5000 and in multiple of Rs1 /-,24-Aug-15,NaN,INF789FB1X41
2428,16230,UTI Asset Management Company Ltd,141665,UTI Nifty Next 50 Exchange Traded Fund,Open Ended,Other ETFs,UTI Nifty Next 50 Exchange Traded Fund,During NFO - Rs. 5000 and in multiples of Rs.1/-,18-Jul-17,NaN,NaN
2429,12273,UTI Asset Management Company Ltd,135321,UTI SENSEX Exchange Traded Fund,Open Ended,Other ETFs,UTI SENSEX Exchange Traded Fund,During NFO Rs5000/- and in multiple of Rs1/-,24-Aug-15,NaN,INF789FB1X58

In [11]:
def sep(temp, ids):
    t = []
    c = 0
    for i in ids:
        t.append(temp[c:i])
        c = i
    return t

In [12]:
tempdata = data

#### adding data

In [13]:
tempdata = create(d['Scheme.NAV.Name'].values, d['Scheme.Minimum.Amount'].values, scheme, tempdata, ids, 'Scheme.Minimum.Amount')
tempdata = create(d['Scheme.NAV.Name'].values, d['Launch.Date'].values, scheme, tempdata, ids, 'Launch.Date')

2725989it [14:13, 3195.67it/s]
2725989it [13:50, 3282.00it/s]

In [16]:
pkl.dump(tempdata, open('fundtype/fundwise.pkl', 'wb'))

In [18]:
tempdata[1]

,Scheme Code,Scheme Name,Net Asset Value,Repurchase Price,Sale Price,Date,Scheme.Minimum.Amount,Launch.Date
291924,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,51.26,51.26,51.26,02-Jan-2013,Rs 1,02-Feb-99
291925,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,51.29,51.29,51.29,03-Jan-2013,Rs 1,02-Feb-99
291926,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,51.39,51.39,51.39,04-Jan-2013,Rs 1,02-Feb-99
291927,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,51.21,51.21,51.21,07-Jan-2013,Rs 1,02-Feb-99
291928,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,51.18,51.18,51.18,08-Jan-2013,Rs 1,02-Feb-99
291929,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,51.09,51.09,51.09,09-Jan-2013,Rs 1,02-Feb-99
291930,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,51.09,51.09,51.09,10-Jan-2013,Rs 1,02-Feb-99
291931,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,50.6,50.6,50.6,11-Jan-2013,Rs 1,02-Feb-99
291932,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,51.13,51.13,51.13,14-Jan-2013,Rs 1,02-Feb-99
291933,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,51.26,51.26,51.26,15-Jan-2013,Rs 1,02-Feb-99
291934,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,50.65,50.65,50.65,16-Jan-2013,Rs 1,02-Feb-99
291935,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,50.86,50.86,50.86,17-Jan-2013,Rs 1,02-Feb-99
291936,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,50.76,50.76,50.76,18-Jan-2013,Rs 1,02-Feb-99
291937,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,50.89,50.89,50.89,21-Jan-2013,Rs 1,02-Feb-99
291938,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,50.62,50.62,50.62,22-Jan-2013,Rs 1,02-Feb-99
291939,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,50.53,50.53,50.53,23-Jan-2013,Rs 1,02-Feb-99
291940,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,50.01,50.01,50.01,24-Jan-2013,Rs 1,02-Feb-99
291941,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,50.49,50.49,50.49,25-Jan-2013,Rs 1,02-Feb-99
291942,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,50.54,50.54,50.54,28-Jan-2013,Rs 1,02-Feb-99
291943,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,50.21,50.21,50.21,29-Jan-2013,Rs 1,02-Feb-99
291944,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,50.22,50.22,50.22,30-Jan-2013,Rs 1,02-Feb-99
291945,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,50.26,50.26,50.26,31-Jan-2013,Rs 1,02-Feb-99
291946,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,50.1,50.1,50.1,01-Feb-2013,Rs 1,02-Feb-99
291947,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,49.91,49.91,49.91,04-Feb-2013,Rs 1,02-Feb-99
291948,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,49.74,49.74,49.74,05-Feb-2013,Rs 1,02-Feb-99
291949,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,49.82,49.82,49.82,06-Feb-2013,Rs 1,02-Feb-99
291950,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,49.64,49.64,49.64,07-Feb-2013,Rs 1,02-Feb-99
291951,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,49.46,49.46,49.46,08-Feb-2013,Rs 1,02-Feb-99
291952,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,49.42,49.42,49.42,11-Feb-2013,Rs 1,02-Feb-99
291953,119660,Aditya Birla Sun Life Tax Plan - Direct Plan -...,49.5,49.5,49.5,12-Feb-2013,Rs 1,02-Feb-99
...,...,...,...,...,...,...,...,...
276663,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,26.6543,26.6543,26.6543,17-Nov-2017,Rs 500/-,15-Nov-99
276664,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,26.7356,26.7356,26.7356,20-Nov-2017,Rs 500/-,15-Nov-99
276665,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,26.8357,26.8357,26.8357,21-Nov-2017,Rs 500/-,15-Nov-99
276666,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,26.8417,26.8417,26.8417,22-Nov-2017,Rs 500/-,15-Nov-99
276667,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,26.8756,26.8756,26.8756,23-Nov-2017,Rs 500/-,15-Nov-99
276668,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,27.0025,27.0025,27.0025,24-Nov-2017,Rs 500/-,15-Nov-99
276669,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,27.0726,27.0726,27.0726,27-Nov-2017,Rs 500/-,15-Nov-99
276670,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,27.0775,27.0775,27.0775,28-Nov-2017,Rs 500/-,15-Nov-99
276671,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,27.0954,27.0954,27.0954,29-Nov-2017,Rs 500/-,15-Nov-99
276672,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,26.8824,26.8824,26.8824,30-Nov-2017,Rs 500/-,15-Nov-99
276673,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,26.5905,26.5905,26.5905,01-Dec-2017,Rs 500/-,15-Nov-99
276674,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,26.6189,26.6189,26.6189,04-Dec-2017,Rs 500/-,15-Nov-99
276675,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,26.5827,26.5827,26.5827,05-Dec-2017,Rs 500/-,15-Nov-99
276676,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,26.4356,26.4356,26.4356,06-Dec-2017,Rs 500/-,15-Nov-99
276677,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,26.8017,26.8017,26.8017,07-Dec-2017,Rs 500/-,15-Nov-99
276678,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,27.0441,27.0441,27.0441,08-Dec-2017,Rs 500/-,15-Nov-99
276679,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,27.1819,27.1819,27.1819,11-Dec-2017,Rs 500/-,15-Nov-99
276680,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,26.9665,26.9665,26.9665,12-Dec-2017,Rs 500/-,15-Nov-99
276681,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,26.7887,26.7887,26.7887,13-Dec-2017,Rs 500/-,15-Nov-99
276682,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,26.8423,26.8423,26.8423,14-Dec-2017,Rs 500/-,15-Nov-99
276683,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,27.0529,27.0529,27.0529,15-Dec-2017,Rs 500/-,15-Nov-99
276684,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,27.2473,27.2473,27.2473,18-Dec-2017,Rs 500/-,15-Nov-99
276685,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,27.5799,27.5799,27.5799,19-Dec-2017,Rs 500/-,15-Nov-99
276686,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,27.636,27.636,27.636,20-Dec-2017,Rs 500/-,15-Nov-99
276687,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,27.7621,27.7621,27.7621,21-Dec-2017,Rs 500/-,15-Nov-99
276688,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,27.8469,27.8469,27.8469,22-Dec-2017,Rs 500/-,15-Nov-99
276689,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,27.938,27.938,27.938,26-Dec-2017,Rs 500/-,15-Nov-99
276690,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,27.8373,27.8373,27.8373,27-Dec-2017,Rs 500/-,15-Nov-99
276691,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,27.8178,27.8178,27.8178,28-Dec-2017,Rs 500/-,15-Nov-99
276692,120714,UTI - Long Term Equity fund (Tax Saving) Direc...,27.916,27.916,27.916,29-Dec-2017,Rs 500/-,15-Nov-99